---
title: "Problems and solutions"
author: "zhangxiaorui0112"
date: "2020/3/19"
output: pdf_document
---

## Error in cat(paste0(contributors$desc, collapse = ", "))

Adding `encoding="UTF-8"`to line 224.
The full command is: `contributors <- read.csv("contributors.csv", stringsAsFactors = FALSE,encoding = "UTF-8")`

## Error in loadNamespace(name) : 'emo'

First, download *Rtools* to my computer, preferably in disk C, and select "Add Rtools to system PATH". Install the package *devtools*, and then input the command: `library(usethis)`, `library(devtools)`, `devtools::install_github(" Hadley /emo")`

## Error in library(dplyr) or Error in loadNamespace(name) :'sessioninfo'

Errors like these indicate missing packages. Using `install.packages()` to solve it. The packages I installed are *dplyr*,*sessioninfo*,*lobstr*, *devtools*, *sloop*,*RSQLite*,*zeallot*,*profvis*,*bench*,*ggbeeswarm*.

## In system(cmd) : 'make' not found

Add *Rtools* to the system path, and restart the computer and Rstudio.

## Warning message: In system2(..., stdout = if (use_file_stdout()) f1 else FALSE, stderr = f2) : '"xelatex"' not found.

First, I tried to install the package *tinytex*, but it didn't solve the problem. Then download *MiKTex*, update the software, and add it to the system path.

## Package fontspec Error: The font "Inconsolata" and "Andale Mono" cannot be found.

Download the *Inconsolata* font and *Andale Mono* font, and place them in the C: \ Windows \ Fonts folder.

